# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
      args:
        - "--maxkb=850"
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.2
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.316
    hooks:
    - id: pyright
      additional_dependencies:
        - "click==8.1.3"
        - "discord.py>=2.3.1,<3.0.0"
        - "jishaku>=2.5.1,<3.0.0"
        - "sqlalchemy[asyncio]>=2.0.17,<3.0.0"
        - "alembic>=1.11.1,<2.0.0"
        - "asyncpg>=0.27.0,<1.0.0"
        - "humanize>=4.7.0,<5.0.0"
