services:
  bot:
    build:
      target: development_build
      args:
        - BOT_ENV=development
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - .:/app
    env_file:
      - config/.env

  database:
    env_file:
      - config/.env
