version: '3.9'

services:
  bot:
    image: incandescent-bot:dev
    container_name: bot
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
      cache_from:
        - "incandescent-bot:dev"
        - "incandescent-bot:latest"
        - "*"
    volumes:
      - .:/bot
    networks:
      - main
    env_file:
      - config/.env
    command: python manage.py runbot

  database:
    image: postgres:15.3-alpine
    container_name: database
    restart: unless-stopped
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - main

networks:
  main:

volumes:
  postgresql:
