version: '3.9'

services:
  database:
    env_file:
      - ./config/.env
  bot:
    env_file:
      - ./config/.env
    volumes:
      - .:/app
    environment:
      - BOT_ENV=development
    build:
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
