name: Deployment

on:
  workflow_run:
    workflows:
      - Publish Docker image
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and deploy
        uses: appleboy/ssh-action@v0.1.10
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker compose -f docker/docker-compose.yml down
            docker compose -f docker/docker-compose.yml build
            docker compose -f docker/docker-compose.yml up -d
