name: Deployment

on:
  workflow_run:
    workflows:
      - Publish Docker image
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker stop $(docker ps -a -q)
            docker pull ghcr.io/bitterteriyaki/incandescent-bot:latest
            docker run --rm -it -d \
              -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
              -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
              -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              ghcr.io/bitterteriyaki/incandescent-bot:latest \
              python manage.py runbot
