name: Deployment

on:
  workflow_run:
    workflows:
      - Publish Docker image
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo 1
